name: Pulsar IO AMQP1_0 Release

on:
  release:
    types: [published]
jobs:
  upload:
    name: Upload Release files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Login streamnative docker hub
        run: docker login -u="${{ secrets.DOCKER_USER }}" -p="${{ secrets.DOCKER_PASSWORD }}"

      - name: build and push docker image
        run: |
          PULSAR_VERSION=`./scripts/dev/get-project-version.py`
          cd io-amqp1_0-impl
          REPO=`mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:exec 2>/dev/null`
          cd -
          IMAGE_REPO=streamnative/${REPO}
          docker build --build-arg PULSAR_VERSION="$PULSAR_VERSION" -t ${IMAGE_REPO}:${PULSAR_VERSION} -f ./image/Dockerfile ./
          docker push ${IMAGE_REPO}:${PULSAR_VERSION}
